import { z } from "zod";

export const insertStudentSchema = z.object({
  name: z.string().min(1, "Name is required"),
  currentLesson: z.string().min(1, "Current lesson is required"),
  status: z.string().min(1, "Status is required"),
  feesPaid: z.boolean().default(false),
  classId: z.string().default("Class 1"),
});

export const insertDailyLogSchema = z.object({
  studentId: z.string().min(1, "Student ID is required"),
  date: z.coerce.date().default(() => new Date()),
  attended: z.boolean().default(true),
  lessonSummary: z.string().optional(),
});

export const insertAchievementSchema = z.object({
  studentId: z.string().min(1, "Student ID is required"),
  level: z.string().min(1, "Level is required"),
  medal: z.string().min(1, "Medal is required"),
  description: z.string().optional(),
});

// Types
export type InsertStudent = z.infer<typeof insertStudentSchema>;
// Add ID for Student as it's generated by Firebase
export type Student = InsertStudent & { id: string };

export type InsertDailyLog = z.infer<typeof insertDailyLogSchema>;
export type DailyLog = InsertDailyLog & { id: string, date: Date };

export type InsertAchievement = z.infer<typeof insertAchievementSchema>;
export type Achievement = InsertAchievement & { id: string };
